"""Seed 3 complete IELTS Listening sections (4 parts × 10 questions = 40 each)."""
from sqlalchemy.orm import Session

from .models import ListeningSection, ListeningPart, ListeningQuestion

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _section_exists(db: Session, title: str) -> bool:
    return db.query(ListeningSection).filter_by(title=title).first() is not None


def _build_questions(part_id_placeholder: str, questions_data: list[dict]) -> list[dict]:
    """Attach part_id placeholder; real id injected after flush."""
    return questions_data


# ---------------------------------------------------------------------------
# Section 1 — Everyday Social Contexts
# ---------------------------------------------------------------------------

SECTION_1 = {
    "title": "Listening Section 1 — Everyday Life",
    "difficulty": 2,
    "parts": [
        {
            "part_number": 1,
            "context_description": "A conversation between two people arranging a community event.",
            "audio_url": "https://example.com/audio/s1p1.mp3",
            "transcript": "[Transcript placeholder for Section 1 Part 1]",
            "questions": [
                {"global_number": 1,  "local_order": 1,  "question_type": "form_completion",
                 "stem": "Event name: ___",
                 "correct_answer": "Summer Fair", "options": None, "answer_variants": ["summer fair"],
                 "group_instruction": "Complete the form. Write NO MORE THAN TWO WORDS for each answer.",
                 "map_image_url": None},
                {"global_number": 2,  "local_order": 2,  "question_type": "form_completion",
                 "stem": "Venue: ___ Park",
                 "correct_answer": "Riverside", "options": None, "answer_variants": ["riverside"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 3,  "local_order": 3,  "question_type": "form_completion",
                 "stem": "Date: ___ July",
                 "correct_answer": "14th", "options": None, "answer_variants": ["14", "fourteenth"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 4,  "local_order": 4,  "question_type": "form_completion",
                 "stem": "Contact phone: ___",
                 "correct_answer": "07712 334 891", "options": None, "answer_variants": None,
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 5,  "local_order": 5,  "question_type": "form_completion",
                 "stem": "Ticket price (adult): £___",
                 "correct_answer": "3.50", "options": None, "answer_variants": ["3.5", "three fifty"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 6,  "local_order": 6,  "question_type": "mcq",
                 "stem": "What will the money raised be used for?",
                 "options": ["A - New playground equipment", "B - Library refurbishment", "C - Sports hall repairs"],
                 "correct_answer": "A", "answer_variants": ["a", "New playground equipment"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
                {"global_number": 7,  "local_order": 7,  "question_type": "mcq",
                 "stem": "Which activity is NOT planned for the event?",
                 "options": ["A - Face painting", "B - Bungee jumping", "C - Live music"],
                 "correct_answer": "B", "answer_variants": ["b", "Bungee jumping"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 8,  "local_order": 8,  "question_type": "mcq",
                 "stem": "When does volunteer registration close?",
                 "options": ["A - 1st July", "B - 7th July", "C - 10th July"],
                 "correct_answer": "C", "answer_variants": ["c", "10th July"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 9,  "local_order": 9,  "question_type": "form_completion",
                 "stem": "Volunteer coordinator name: ___",
                 "correct_answer": "Sandra", "options": None, "answer_variants": ["sandra"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 10, "local_order": 10, "question_type": "form_completion",
                 "stem": "Number of stalls available: ___",
                 "correct_answer": "24", "options": None, "answer_variants": ["twenty-four", "twenty four"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 2,
            "context_description": "A tour guide describes facilities at a leisure centre.",
            "audio_url": "https://example.com/audio/s1p2.mp3",
            "transcript": "[Transcript placeholder for Section 1 Part 2]",
            "questions": [
                {"global_number": 11, "local_order": 1, "question_type": "map_labeling",
                 "stem": "Label the map. What is in location A?",
                 "options": ["Café", "Reception", "Swimming pool", "Car park", "Gym", "Sauna"],
                 "correct_answer": "Reception", "answer_variants": ["reception"],
                 "group_instruction": "Label the plan below. Choose SIX answers from the box.",
                 "map_image_url": "https://example.com/maps/leisure_centre.png"},
                {"global_number": 12, "local_order": 2, "question_type": "map_labeling",
                 "stem": "What is in location B?",
                 "options": ["Café", "Reception", "Swimming pool", "Car park", "Gym", "Sauna"],
                 "correct_answer": "Café", "answer_variants": ["café", "cafe"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 13, "local_order": 3, "question_type": "map_labeling",
                 "stem": "What is in location C?",
                 "options": ["Café", "Reception", "Swimming pool", "Car park", "Gym", "Sauna"],
                 "correct_answer": "Gym", "answer_variants": ["gym"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 14, "local_order": 4, "question_type": "map_labeling",
                 "stem": "What is in location D?",
                 "options": ["Café", "Reception", "Swimming pool", "Car park", "Gym", "Sauna"],
                 "correct_answer": "Swimming pool", "answer_variants": ["swimming pool", "pool"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 15, "local_order": 5, "question_type": "map_labeling",
                 "stem": "What is in location E?",
                 "options": ["Café", "Reception", "Swimming pool", "Car park", "Gym", "Sauna"],
                 "correct_answer": "Sauna", "answer_variants": ["sauna"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 16, "local_order": 6, "question_type": "note_completion",
                 "stem": "Annual membership fee: £___ per year",
                 "correct_answer": "420", "options": None, "answer_variants": ["four hundred and twenty"],
                 "group_instruction": "Complete the notes. Write ONE NUMBER for each answer.",
                 "map_image_url": None},
                {"global_number": 17, "local_order": 7, "question_type": "note_completion",
                 "stem": "Off-peak hours: ___ to ___",
                 "correct_answer": "9am to 4pm", "options": None, "answer_variants": ["9 to 4", "9:00-16:00"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 18, "local_order": 8, "question_type": "note_completion",
                 "stem": "Free ___ class every Saturday morning",
                 "correct_answer": "yoga", "options": None, "answer_variants": None,
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 19, "local_order": 9, "question_type": "note_completion",
                 "stem": "Children must be accompanied by an adult until age ___",
                 "correct_answer": "16", "options": None, "answer_variants": ["sixteen"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 20, "local_order": 10, "question_type": "mcq",
                 "stem": "Which parking option is free for members?",
                 "options": ["A - All day parking", "B - First two hours only", "C - Weekends only"],
                 "correct_answer": "B", "answer_variants": ["b", "First two hours only"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
            ],
        },
        {
            "part_number": 3,
            "context_description": "Two university students discuss a group research project on urban transport.",
            "audio_url": "https://example.com/audio/s1p3.mp3",
            "transcript": "[Transcript placeholder for Section 1 Part 3]",
            "questions": [
                {"global_number": 21, "local_order": 1, "question_type": "mcq",
                 "stem": "What is the main focus of their project?",
                 "options": ["A - Cycling infrastructure", "B - Electric buses", "C - Pedestrian zones"],
                 "correct_answer": "B", "answer_variants": ["b", "Electric buses"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
                {"global_number": 22, "local_order": 2, "question_type": "mcq",
                 "stem": "Where will they find their primary data?",
                 "options": ["A - Online surveys", "B - Government transport reports", "C - Interviews with commuters"],
                 "correct_answer": "C", "answer_variants": ["c", "Interviews with commuters"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 23, "local_order": 3, "question_type": "mcq",
                 "stem": "When is their presentation deadline?",
                 "options": ["A - Week 8", "B - Week 10", "C - Week 12"],
                 "correct_answer": "B", "answer_variants": ["b", "Week 10"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 24, "local_order": 4, "question_type": "matching",
                 "stem": "Match each student to their assigned task.",
                 "options": {"Maria": "Literature review", "James": "Data collection", "Both": "Final report"},
                 "correct_answer": "Maria=Literature review;James=Data collection",
                 "answer_variants": None,
                 "group_instruction": "Match the students (24-26) with the tasks (A-F). Write the correct letter.",
                 "map_image_url": None},
                {"global_number": 25, "local_order": 5, "question_type": "matching",
                 "stem": "Who is responsible for creating visual aids?",
                 "options": {"A": "Maria only", "B": "James only", "C": "Both students", "D": "Neither"},
                 "correct_answer": "A", "answer_variants": ["a", "Maria only"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 26, "local_order": 6, "question_type": "matching",
                 "stem": "Who will contact the transport authority?",
                 "options": {"A": "Maria only", "B": "James only", "C": "Both students", "D": "Neither"},
                 "correct_answer": "B", "answer_variants": ["b", "James only"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 27, "local_order": 7, "question_type": "sentence_completion",
                 "stem": "The students agree that the biggest challenge will be ___.",
                 "correct_answer": "recruiting participants", "options": None,
                 "answer_variants": ["finding participants", "participant recruitment"],
                 "group_instruction": "Complete each sentence with NO MORE THAN THREE WORDS.",
                 "map_image_url": None},
                {"global_number": 28, "local_order": 8, "question_type": "sentence_completion",
                 "stem": "They plan to use ___ to record interviews.",
                 "correct_answer": "voice recorder", "options": None,
                 "answer_variants": ["a voice recorder", "audio recorder"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 29, "local_order": 9, "question_type": "sentence_completion",
                 "stem": "The supervisor suggested reading the ___ report first.",
                 "correct_answer": "2022 transport", "options": None,
                 "answer_variants": ["transport 2022"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 30, "local_order": 10, "question_type": "sentence_completion",
                 "stem": "They will meet again on ___.",
                 "correct_answer": "Thursday afternoon", "options": None,
                 "answer_variants": ["thursday", "Thursday"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 4,
            "context_description": "A lecturer speaks about the history of urban planning in 20th-century Europe.",
            "audio_url": "https://example.com/audio/s1p4.mp3",
            "transcript": "[Transcript placeholder for Section 1 Part 4]",
            "questions": [
                {"global_number": 31, "local_order": 1, "question_type": "note_completion",
                 "stem": "The lecture covers urban planning from ___ to ___.",
                 "correct_answer": "1900 to 1990", "options": None,
                 "answer_variants": ["1900-1990", "nineteen hundred to nineteen ninety"],
                 "group_instruction": "Complete the notes. Write NO MORE THAN THREE WORDS AND/OR A NUMBER.",
                 "map_image_url": None},
                {"global_number": 32, "local_order": 2, "question_type": "note_completion",
                 "stem": "The first planned city discussed is ___.",
                 "correct_answer": "Letchworth", "options": None, "answer_variants": None,
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 33, "local_order": 3, "question_type": "note_completion",
                 "stem": "Letchworth was designed by ___.",
                 "correct_answer": "Ebenezer Howard", "options": None,
                 "answer_variants": ["Howard", "E. Howard"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 34, "local_order": 4, "question_type": "note_completion",
                 "stem": "The 'Garden City' concept aimed to combine ___ and rural life.",
                 "correct_answer": "urban", "options": None, "answer_variants": ["city", "town"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 35, "local_order": 5, "question_type": "note_completion",
                 "stem": "Post-war housing blocks were criticised for causing social ___.",
                 "correct_answer": "isolation", "options": None,
                 "answer_variants": ["problems", "issues"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 36, "local_order": 6, "question_type": "mcq",
                 "stem": "What does the lecturer say about Le Corbusier's plans?",
                 "options": ["A - They were never built", "B - They influenced modern housing", "C - They were too expensive"],
                 "correct_answer": "B", "answer_variants": ["b", "They influenced modern housing"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
                {"global_number": 37, "local_order": 7, "question_type": "mcq",
                 "stem": "Which country is cited as the best example of post-war urban renewal?",
                 "options": ["A - France", "B - Sweden", "C - Germany"],
                 "correct_answer": "B", "answer_variants": ["b", "Sweden"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 38, "local_order": 8, "question_type": "note_completion",
                 "stem": "By 1970, ___ % of Europeans lived in cities.",
                 "correct_answer": "67", "options": None, "answer_variants": ["sixty-seven", "sixty seven"],
                 "group_instruction": "Complete the notes.", "map_image_url": None},
                {"global_number": 39, "local_order": 9, "question_type": "note_completion",
                 "stem": "The movement to reclaim city centres began in the ___.",
                 "correct_answer": "1980s", "options": None,
                 "answer_variants": ["eighties", "late twentieth century"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 40, "local_order": 10, "question_type": "note_completion",
                 "stem": "The lecturer recommends reading the book '___ City' for next week.",
                 "correct_answer": "Invisible", "options": None, "answer_variants": ["invisible"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
    ],
}

# ---------------------------------------------------------------------------
# Section 2 — Academic and Professional Contexts
# ---------------------------------------------------------------------------

SECTION_2 = {
    "title": "Listening Section 2 — Academic & Professional",
    "difficulty": 3,
    "parts": [
        {
            "part_number": 1,
            "context_description": "Two colleagues discuss plans for a company relocation.",
            "audio_url": "https://example.com/audio/s2p1.mp3",
            "transcript": "[Transcript placeholder for Section 2 Part 1]",
            "questions": [
                {"global_number": 1,  "local_order": 1,  "question_type": "form_completion",
                 "stem": "New office address: ___ Business Park",
                 "correct_answer": "Greenfield", "options": None, "answer_variants": ["greenfield"],
                 "group_instruction": "Complete the form. Write NO MORE THAN TWO WORDS AND/OR A NUMBER.",
                 "map_image_url": None},
                {"global_number": 2,  "local_order": 2,  "question_type": "form_completion",
                 "stem": "Planned move date: ___ March",
                 "correct_answer": "22nd", "options": None, "answer_variants": ["22", "twenty-second"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 3,  "local_order": 3,  "question_type": "form_completion",
                 "stem": "Number of new workstations: ___",
                 "correct_answer": "85", "options": None, "answer_variants": ["eighty-five"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 4,  "local_order": 4,  "question_type": "mcq",
                 "stem": "What is the main reason for the relocation?",
                 "options": ["A - Lower rent costs", "B - Closer to clients", "C - Better transport links"],
                 "correct_answer": "C", "answer_variants": ["c", "Better transport links"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
                {"global_number": 5,  "local_order": 5,  "question_type": "mcq",
                 "stem": "Which department will move first?",
                 "options": ["A - Finance", "B - Marketing", "C - IT"],
                 "correct_answer": "C", "answer_variants": ["c", "IT"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 6,  "local_order": 6,  "question_type": "form_completion",
                 "stem": "Name of removal company: ___ Logistics",
                 "correct_answer": "Swift", "options": None, "answer_variants": ["swift"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 7,  "local_order": 7,  "question_type": "form_completion",
                 "stem": "Employee helpline opens: ___ February",
                 "correct_answer": "1st", "options": None, "answer_variants": ["1", "first"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 8,  "local_order": 8,  "question_type": "mcq",
                 "stem": "What parking arrangement has been agreed?",
                 "options": ["A - All staff get a space", "B - First come, first served", "C - Permits for senior staff only"],
                 "correct_answer": "C", "answer_variants": ["c"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 9,  "local_order": 9,  "question_type": "form_completion",
                 "stem": "Staff survey closing date: ___ January",
                 "correct_answer": "31st", "options": None, "answer_variants": ["31", "thirty-first"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 10, "local_order": 10, "question_type": "form_completion",
                 "stem": "Contact email prefix for queries: relocation@___.co.uk",
                 "correct_answer": "example", "options": None, "answer_variants": None,
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 2,
            "context_description": "A radio presenter talks about a new wildlife conservation programme.",
            "audio_url": "https://example.com/audio/s2p2.mp3",
            "transcript": "[Transcript placeholder for Section 2 Part 2]",
            "questions": [
                {"global_number": 11, "local_order": 1, "question_type": "note_completion",
                 "stem": "The programme protects ___ species of birds.",
                 "correct_answer": "47", "options": None, "answer_variants": ["forty-seven"],
                 "group_instruction": "Complete the notes. Write ONE WORD AND/OR A NUMBER.",
                 "map_image_url": None},
                {"global_number": 12, "local_order": 2, "question_type": "note_completion",
                 "stem": "The reserve covers ___ hectares.",
                 "correct_answer": "3,200", "options": None, "answer_variants": ["3200", "three thousand two hundred"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 13, "local_order": 3, "question_type": "note_completion",
                 "stem": "Main funding comes from the ___ Foundation.",
                 "correct_answer": "Bellwood", "options": None, "answer_variants": ["bellwood"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 14, "local_order": 4, "question_type": "mcq",
                 "stem": "What threat does the programme primarily address?",
                 "options": ["A - Habitat loss", "B - Illegal hunting", "C - Climate change"],
                 "correct_answer": "A", "answer_variants": ["a", "Habitat loss"],
                 "group_instruction": "Choose the correct letter.", "map_image_url": None},
                {"global_number": 15, "local_order": 5, "question_type": "mcq",
                 "stem": "How can members of the public get involved?",
                 "options": ["A - Donate online", "B - Volunteer on weekends", "C - Adopt a species"],
                 "correct_answer": "B", "answer_variants": ["b", "Volunteer on weekends"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 16, "local_order": 6, "question_type": "map_labeling",
                 "stem": "What is located at point X on the reserve map?",
                 "options": ["Visitor centre", "Breeding enclosure", "Water treatment plant", "Car park", "Hide 1", "Research lab"],
                 "correct_answer": "Breeding enclosure", "answer_variants": ["breeding enclosure"],
                 "group_instruction": "Label the map. Choose from the box.",
                 "map_image_url": "https://example.com/maps/wildlife_reserve.png"},
                {"global_number": 17, "local_order": 7, "question_type": "map_labeling",
                 "stem": "What is at point Y?",
                 "options": ["Visitor centre", "Breeding enclosure", "Water treatment plant", "Car park", "Hide 1", "Research lab"],
                 "correct_answer": "Research lab", "answer_variants": ["research lab", "laboratory"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 18, "local_order": 8, "question_type": "map_labeling",
                 "stem": "What is at point Z?",
                 "options": ["Visitor centre", "Breeding enclosure", "Water treatment plant", "Car park", "Hide 1", "Research lab"],
                 "correct_answer": "Hide 1", "answer_variants": ["hide 1", "hide"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 19, "local_order": 9, "question_type": "note_completion",
                 "stem": "Guided tours depart at ___ and 2 pm daily.",
                 "correct_answer": "10 am", "options": None, "answer_variants": ["10am", "10:00"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 20, "local_order": 10, "question_type": "note_completion",
                 "stem": "School groups receive a ___ % discount.",
                 "correct_answer": "30", "options": None, "answer_variants": ["thirty"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 3,
            "context_description": "A tutor and student discuss a dissertation on renewable energy policy.",
            "audio_url": "https://example.com/audio/s2p3.mp3",
            "transcript": "[Transcript placeholder for Section 2 Part 3]",
            "questions": [
                {"global_number": 21, "local_order": 1, "question_type": "mcq",
                 "stem": "What is the student's dissertation topic?",
                 "options": ["A - Solar energy subsidies", "B - Wind farm regulations", "C - National grid reform"],
                 "correct_answer": "A", "answer_variants": ["a", "Solar energy subsidies"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
                {"global_number": 22, "local_order": 2, "question_type": "mcq",
                 "stem": "Which chapter does the tutor say needs the most work?",
                 "options": ["A - Introduction", "B - Literature review", "C - Methodology"],
                 "correct_answer": "C", "answer_variants": ["c", "Methodology"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 23, "local_order": 3, "question_type": "sentence_completion",
                 "stem": "The student will add two more ___ to support the argument.",
                 "correct_answer": "case studies", "options": None, "answer_variants": ["case studies from Europe"],
                 "group_instruction": "Complete each sentence with NO MORE THAN THREE WORDS.",
                 "map_image_url": None},
                {"global_number": 24, "local_order": 4, "question_type": "sentence_completion",
                 "stem": "The tutor recommends consulting the ___ database for recent policy papers.",
                 "correct_answer": "JSTOR", "options": None, "answer_variants": ["jstor"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 25, "local_order": 5, "question_type": "sentence_completion",
                 "stem": "The first full draft is due on ___.",
                 "correct_answer": "3rd April", "options": None, "answer_variants": ["April 3rd", "3 April"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 26, "local_order": 6, "question_type": "matching",
                 "stem": "Match each section to the tutor's feedback.",
                 "options": {"Introduction": "A - Needs a clearer thesis", "Literature review": "B - Good breadth", "Methodology": "C - Expand sample size"},
                 "correct_answer": "Introduction=A;Literature review=B;Methodology=C",
                 "answer_variants": None, "group_instruction": "Match sections to feedback.", "map_image_url": None},
                {"global_number": 27, "local_order": 7, "question_type": "matching",
                 "stem": "Which source does the tutor rate as most credible?",
                 "options": {"A": "Government white paper", "B": "Academic journal", "C": "NGO report", "D": "News article"},
                 "correct_answer": "A", "answer_variants": ["a", "Government white paper"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 28, "local_order": 8, "question_type": "mcq",
                 "stem": "What does the tutor suggest the student do before resubmitting?",
                 "options": ["A - Attend a workshop", "B - Interview a policy expert", "C - Read a specific textbook"],
                 "correct_answer": "B", "answer_variants": ["b"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 29, "local_order": 9, "question_type": "sentence_completion",
                 "stem": "Their next meeting is scheduled for ___ at 10 am.",
                 "correct_answer": "next Monday", "options": None, "answer_variants": ["Monday"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 30, "local_order": 10, "question_type": "sentence_completion",
                 "stem": "The student needs to email the updated ___ before the meeting.",
                 "correct_answer": "chapter outline", "options": None, "answer_variants": ["outline"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 4,
            "context_description": "A guest lecturer discusses the psychology of decision-making in economics.",
            "audio_url": "https://example.com/audio/s2p4.mp3",
            "transcript": "[Transcript placeholder for Section 2 Part 4]",
            "questions": [
                {"global_number": 31, "local_order": 1, "question_type": "note_completion",
                 "stem": "The field discussed is called ___ economics.",
                 "correct_answer": "behavioural", "options": None, "answer_variants": ["behavioral"],
                 "group_instruction": "Complete the notes. Write NO MORE THAN TWO WORDS.",
                 "map_image_url": None},
                {"global_number": 32, "local_order": 2, "question_type": "note_completion",
                 "stem": "Kahneman and Tversky introduced the concept of ___ theory.",
                 "correct_answer": "prospect", "options": None, "answer_variants": None,
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 33, "local_order": 3, "question_type": "note_completion",
                 "stem": "People feel losses ___ times more strongly than equivalent gains.",
                 "correct_answer": "twice", "options": None, "answer_variants": ["2", "two"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 34, "local_order": 4, "question_type": "note_completion",
                 "stem": "The '___ effect' explains why people stick with default options.",
                 "correct_answer": "status quo", "options": None, "answer_variants": ["status-quo"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 35, "local_order": 5, "question_type": "mcq",
                 "stem": "What example does the lecturer use to illustrate anchoring?",
                 "options": ["A - Salary negotiation", "B - Supermarket pricing", "C - House valuations"],
                 "correct_answer": "C", "answer_variants": ["c", "House valuations"],
                 "group_instruction": "Choose the correct letter.", "map_image_url": None},
                {"global_number": 36, "local_order": 6, "question_type": "mcq",
                 "stem": "Which bias leads investors to hold losing stocks too long?",
                 "options": ["A - Confirmation bias", "B - Sunk cost fallacy", "C - Recency bias"],
                 "correct_answer": "B", "answer_variants": ["b", "Sunk cost fallacy"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 37, "local_order": 7, "question_type": "note_completion",
                 "stem": "Thaler won the Nobel Prize in Economics in ___.",
                 "correct_answer": "2017", "options": None, "answer_variants": ["twenty seventeen"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 38, "local_order": 8, "question_type": "note_completion",
                 "stem": "The lecture mentions ___ as a real-world application of nudge theory.",
                 "correct_answer": "pension enrolment", "options": None,
                 "answer_variants": ["auto-enrolment", "automatic enrolment"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 39, "local_order": 9, "question_type": "mcq",
                 "stem": "What criticism of behavioural economics does the lecturer acknowledge?",
                 "options": ["A - It ignores culture", "B - Lab findings don't scale", "C - It lacks mathematical models"],
                 "correct_answer": "B", "answer_variants": ["b", "Lab findings don't scale"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 40, "local_order": 10, "question_type": "note_completion",
                 "stem": "Recommended reading: '___ and Irrational'",
                 "correct_answer": "Predictably", "options": None, "answer_variants": ["predictably"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
    ],
}

# ---------------------------------------------------------------------------
# Section 3 — Advanced Academic Topics
# ---------------------------------------------------------------------------

SECTION_3 = {
    "title": "Listening Section 3 — Advanced Academic",
    "difficulty": 4,
    "parts": [
        {
            "part_number": 1,
            "context_description": "A student calls a university admissions office to enquire about a postgraduate course.",
            "audio_url": "https://example.com/audio/s3p1.mp3",
            "transcript": "[Transcript placeholder for Section 3 Part 1]",
            "questions": [
                {"global_number": 1,  "local_order": 1,  "question_type": "form_completion",
                 "stem": "Course title: MSc in ___ Management",
                 "correct_answer": "Environmental", "options": None, "answer_variants": ["environmental"],
                 "group_instruction": "Complete the form. Write NO MORE THAN TWO WORDS AND/OR A NUMBER.",
                 "map_image_url": None},
                {"global_number": 2,  "local_order": 2,  "question_type": "form_completion",
                 "stem": "Application deadline: ___ October",
                 "correct_answer": "15th", "options": None, "answer_variants": ["15", "fifteenth"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 3,  "local_order": 3,  "question_type": "form_completion",
                 "stem": "Annual tuition fee (home students): £___",
                 "correct_answer": "9,250", "options": None, "answer_variants": ["9250", "9,250.00"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 4,  "local_order": 4,  "question_type": "form_completion",
                 "stem": "Reference required from ___ academic",
                 "correct_answer": "one", "options": None, "answer_variants": ["1"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 5,  "local_order": 5,  "question_type": "mcq",
                 "stem": "What does the admissions officer say about work experience?",
                 "options": ["A - Compulsory", "B - Strongly recommended", "C - Not required"],
                 "correct_answer": "B", "answer_variants": ["b", "Strongly recommended"],
                 "group_instruction": "Choose the correct letter, A, B or C.", "map_image_url": None},
                {"global_number": 6,  "local_order": 6,  "question_type": "mcq",
                 "stem": "When is the open day?",
                 "options": ["A - 5th November", "B - 12th November", "C - 19th November"],
                 "correct_answer": "A", "answer_variants": ["a", "5th November"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 7,  "local_order": 7,  "question_type": "form_completion",
                 "stem": "Student accommodation deposit: £___",
                 "correct_answer": "500", "options": None, "answer_variants": ["five hundred"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 8,  "local_order": 8,  "question_type": "form_completion",
                 "stem": "IELTS minimum score required: ___",
                 "correct_answer": "6.5", "options": None, "answer_variants": ["6.5 overall"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 9,  "local_order": 9,  "question_type": "mcq",
                 "stem": "Which scholarship is mentioned as available to international students?",
                 "options": ["A - Chevening", "B - Rhodes", "C - Commonwealth"],
                 "correct_answer": "A", "answer_variants": ["a", "Chevening"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 10, "local_order": 10, "question_type": "form_completion",
                 "stem": "Admissions officer direct email: admissions@___.ac.uk",
                 "correct_answer": "example", "options": None, "answer_variants": None,
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 2,
            "context_description": "A museum guide describes an exhibition on ancient Egyptian artefacts.",
            "audio_url": "https://example.com/audio/s3p2.mp3",
            "transcript": "[Transcript placeholder for Section 3 Part 2]",
            "questions": [
                {"global_number": 11, "local_order": 1, "question_type": "map_labeling",
                 "stem": "What is displayed in Room A?",
                 "options": ["Jewellery", "Mummies", "Papyrus scrolls", "Pottery", "Statues", "Coins"],
                 "correct_answer": "Mummies", "answer_variants": ["mummies"],
                 "group_instruction": "Label the museum plan. Choose from the box.",
                 "map_image_url": "https://example.com/maps/museum_plan.png"},
                {"global_number": 12, "local_order": 2, "question_type": "map_labeling",
                 "stem": "What is in Room B?",
                 "options": ["Jewellery", "Mummies", "Papyrus scrolls", "Pottery", "Statues", "Coins"],
                 "correct_answer": "Jewellery", "answer_variants": ["jewellery", "jewelry"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 13, "local_order": 3, "question_type": "map_labeling",
                 "stem": "What is in Room C?",
                 "options": ["Jewellery", "Mummies", "Papyrus scrolls", "Pottery", "Statues", "Coins"],
                 "correct_answer": "Statues", "answer_variants": ["statues"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 14, "local_order": 4, "question_type": "note_completion",
                 "stem": "The oldest artefact dates to ___ BC.",
                 "correct_answer": "3100", "options": None, "answer_variants": ["3,100"],
                 "group_instruction": "Complete the notes.", "map_image_url": None},
                {"global_number": 15, "local_order": 5, "question_type": "note_completion",
                 "stem": "The exhibition runs until ___ December.",
                 "correct_answer": "18th", "options": None, "answer_variants": ["18", "eighteenth"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 16, "local_order": 6, "question_type": "mcq",
                 "stem": "Photography is permitted:",
                 "options": ["A - Everywhere", "B - Only in Rooms A and B", "C - Nowhere in the exhibition"],
                 "correct_answer": "B", "answer_variants": ["b"],
                 "group_instruction": "Choose the correct letter.", "map_image_url": None},
                {"global_number": 17, "local_order": 7, "question_type": "mcq",
                 "stem": "The guided tour lasts approximately:",
                 "options": ["A - 45 minutes", "B - 60 minutes", "C - 90 minutes"],
                 "correct_answer": "C", "answer_variants": ["c", "90 minutes"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 18, "local_order": 8, "question_type": "note_completion",
                 "stem": "Group discount applies to parties of ___ or more.",
                 "correct_answer": "10", "options": None, "answer_variants": ["ten"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 19, "local_order": 9, "question_type": "note_completion",
                 "stem": "Children under ___ enter free.",
                 "correct_answer": "5", "options": None, "answer_variants": ["five"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 20, "local_order": 10, "question_type": "note_completion",
                 "stem": "The gift shop closes at ___ on weekdays.",
                 "correct_answer": "6 pm", "options": None, "answer_variants": ["6pm", "18:00"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 3,
            "context_description": "Two students and a tutor discuss a group presentation on marine pollution.",
            "audio_url": "https://example.com/audio/s3p3.mp3",
            "transcript": "[Transcript placeholder for Section 3 Part 3]",
            "questions": [
                {"global_number": 21, "local_order": 1, "question_type": "mcq",
                 "stem": "What aspect of marine pollution will they focus on?",
                 "options": ["A - Microplastics", "B - Oil spills", "C - Agricultural runoff"],
                 "correct_answer": "A", "answer_variants": ["a", "Microplastics"],
                 "group_instruction": "Choose the correct letter.", "map_image_url": None},
                {"global_number": 22, "local_order": 2, "question_type": "mcq",
                 "stem": "How long is the presentation?",
                 "options": ["A - 10 minutes", "B - 15 minutes", "C - 20 minutes"],
                 "correct_answer": "C", "answer_variants": ["c", "20 minutes"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 23, "local_order": 3, "question_type": "matching",
                 "stem": "Match each student to their section.",
                 "options": {"Priya": "A - Introduction and background", "Tom": "B - Case studies", "Both": "C - Conclusion"},
                 "correct_answer": "Priya=A;Tom=B", "answer_variants": None,
                 "group_instruction": "Match students to sections.", "map_image_url": None},
                {"global_number": 24, "local_order": 4, "question_type": "matching",
                 "stem": "Who will handle the Q&A session?",
                 "options": {"A": "Priya only", "B": "Tom only", "C": "Both", "D": "The tutor"},
                 "correct_answer": "C", "answer_variants": ["c", "Both"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 25, "local_order": 5, "question_type": "sentence_completion",
                 "stem": "The tutor advises them to cite sources from peer-reviewed ___ only.",
                 "correct_answer": "journals", "options": None, "answer_variants": ["academic journals"],
                 "group_instruction": "Complete the sentence with NO MORE THAN TWO WORDS.", "map_image_url": None},
                {"global_number": 26, "local_order": 6, "question_type": "sentence_completion",
                 "stem": "Visual aids should be limited to ___ slides.",
                 "correct_answer": "twelve", "options": None, "answer_variants": ["12"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 27, "local_order": 7, "question_type": "sentence_completion",
                 "stem": "They must submit a ___ week before the presentation.",
                 "correct_answer": "script", "options": None, "answer_variants": ["written script"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 28, "local_order": 8, "question_type": "mcq",
                 "stem": "What does the tutor say about statistics?",
                 "options": ["A - Avoid them", "B - Use only current figures", "C - Explain each one clearly"],
                 "correct_answer": "C", "answer_variants": ["c"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 29, "local_order": 9, "question_type": "sentence_completion",
                 "stem": "They will rehearse on ___ at 2 pm.",
                 "correct_answer": "Wednesday", "options": None, "answer_variants": ["wednesday"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 30, "local_order": 10, "question_type": "mcq",
                 "stem": "What is the main marking criterion?",
                 "options": ["A - Content accuracy", "B - Delivery and timing", "C - Slide design"],
                 "correct_answer": "A", "answer_variants": ["a", "Content accuracy"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
        {
            "part_number": 4,
            "context_description": "A professor lectures on the development of artificial intelligence and its societal impact.",
            "audio_url": "https://example.com/audio/s3p4.mp3",
            "transcript": "[Transcript placeholder for Section 3 Part 4]",
            "questions": [
                {"global_number": 31, "local_order": 1, "question_type": "note_completion",
                 "stem": "The term 'Artificial Intelligence' was coined in ___.",
                 "correct_answer": "1956", "options": None, "answer_variants": ["nineteen fifty-six"],
                 "group_instruction": "Complete the notes. Write NO MORE THAN TWO WORDS AND/OR A NUMBER.",
                 "map_image_url": None},
                {"global_number": 32, "local_order": 2, "question_type": "note_completion",
                 "stem": "The Turing Test was proposed by Alan Turing in ___.",
                 "correct_answer": "1950", "options": None, "answer_variants": ["nineteen fifty"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 33, "local_order": 3, "question_type": "note_completion",
                 "stem": "The first AI winter occurred in the ___.",
                 "correct_answer": "1970s", "options": None, "answer_variants": ["seventies", "late 1970s"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 34, "local_order": 4, "question_type": "note_completion",
                 "stem": "Deep learning relies on ___ neural networks.",
                 "correct_answer": "deep", "options": None, "answer_variants": ["multilayer"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 35, "local_order": 5, "question_type": "mcq",
                 "stem": "What does the professor identify as the biggest current risk of AI?",
                 "options": ["A - Job displacement", "B - Algorithmic bias", "C - Autonomous weapons"],
                 "correct_answer": "B", "answer_variants": ["b", "Algorithmic bias"],
                 "group_instruction": "Choose the correct letter.", "map_image_url": None},
                {"global_number": 36, "local_order": 6, "question_type": "mcq",
                 "stem": "Which industry does the professor say has benefited most from AI so far?",
                 "options": ["A - Healthcare", "B - Finance", "C - Transport"],
                 "correct_answer": "A", "answer_variants": ["a", "Healthcare"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 37, "local_order": 7, "question_type": "note_completion",
                 "stem": "The EU AI Act was proposed in ___.",
                 "correct_answer": "2021", "options": None, "answer_variants": ["twenty twenty-one"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 38, "local_order": 8, "question_type": "note_completion",
                 "stem": "The professor argues that AI governance must be ___.",
                 "correct_answer": "international", "options": None,
                 "answer_variants": ["global", "internationally coordinated"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 39, "local_order": 9, "question_type": "mcq",
                 "stem": "What does the professor say about general AI (AGI)?",
                 "options": ["A - It already exists", "B - It is 10 years away", "C - Its timeline is uncertain"],
                 "correct_answer": "C", "answer_variants": ["c"],
                 "group_instruction": None, "map_image_url": None},
                {"global_number": 40, "local_order": 10, "question_type": "note_completion",
                 "stem": "Recommended reading: '___ Intelligence' by Stuart Russell.",
                 "correct_answer": "Human Compatible", "options": None,
                 "answer_variants": ["human compatible"],
                 "group_instruction": None, "map_image_url": None},
            ],
        },
    ],
}

ALL_SECTIONS = [SECTION_1, SECTION_2, SECTION_3]

# ---------------------------------------------------------------------------
# Seed function
# ---------------------------------------------------------------------------

def seed(db: Session) -> None:
    for section_data in ALL_SECTIONS:
        if _section_exists(db, section_data["title"]):
            continue

        section = ListeningSection(
            title=section_data["title"],
            difficulty=section_data["difficulty"],
        )
        db.add(section)
        db.flush()

        for part_data in section_data["parts"]:
            part = ListeningPart(
                section_id=section.id,
                part_number=part_data["part_number"],
                context_description=part_data.get("context_description"),
                audio_url=part_data.get("audio_url"),
                transcript=part_data.get("transcript"),
            )
            db.add(part)
            db.flush()

            for q in part_data["questions"]:
                question = ListeningQuestion(
                    part_id=part.id,
                    global_number=q["global_number"],
                    local_order=q["local_order"],
                    question_type=q["question_type"],
                    stem=q["stem"],
                    options=q.get("options"),
                    correct_answer=q["correct_answer"],
                    answer_variants=q.get("answer_variants"),
                    group_instruction=q.get("group_instruction"),
                    map_image_url=q.get("map_image_url"),
                )
                db.add(question)

    db.commit()
